### ISSUE TITLE
Cant enable in gedit 3.28.1

### ISSUE THREAD

**Issue by lefrankleal** [addiks/gedit-phpide#19]
Hello, am trying to enable this plugin in gedit 3.28.1 with Ubuntu 18.04 and Python 2.7.15rc1 but every time the plugins goes disabled and show me a red icon next to the plugin entry.

Some1 could help me? thanks
![captura de pantalla de 2018-07-17 11-24-13](https://user-images.githubusercontent.com/16306402/42831602-60b99596-89b4-11e8-822d-95dd75ada044.png)

**Comment by jasmines** [comment]
same here with gedit 3.32.0-3, ubuntu 19.04, python 2.7.16-1

`(org.gnome.gedit:24101): libpeas-WARNING **: 12:14:31.956: Error importing plugin 'addiks-phpide':
Traceback (most recent call last):
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mauro/.local/share/gedit/plugins/addiks_phpide/addiks-phpide.py", line 17, in <module>
    from addiks_phpide.AddiksPHPIDEApp import AddiksPHPIDEApp
  File "/home/mauro/.local/share/gedit/plugins/addiks_phpide/addiks_phpide/AddiksPHPIDEApp.py", line 23, in <module>
    from .AddiksPhpGladeHandler import AddiksPhpGladeHandler
  File "/home/mauro/.local/share/gedit/plugins/addiks_phpide/addiks_phpide/AddiksPhpGladeHandler.py", line 27, in <module>
    from .PHP.GraphMLExporter import GraphMLExporter
  File "/home/mauro/.local/share/gedit/plugins/addiks_phpide/addiks_phpide/PHP/GraphMLExporter.py", line 19, in <module>
    from lxml import etree as xml
ModuleNotFoundError: No module named 'lxml'

(org.gnome.gedit:24101): libpeas-WARNING **: 12:14:31.956: Error loading plugin 'addiks-phpide'
`

**Comment by jasmines** [comment]
solved with:
sudo apt install -y python3-pip
pip3 install lxml

**Comment by jasmines** [comment]
anyway PHP menu doesn't show up...

**Comment by lefrankleal** [comment]
> anyway PHP menu doesn't show up...

sorry, i've left gedit back and actually am using other options
