### ISSUE TITLE
Gedit can not activate the plugin

### ISSUE THREAD

**Issue by wblessen** [addiks/gedit-phpide#21]
I'm using Ubuntu 22.04 and tried to use the Plugin for PHP Development.

Gedit is hanging, when I try to activate the plugin in the Settings.

Command Line tells me:

```
Traceback (most recent call last):
  File "/home/wolfgang/.local/share/gedit/plugins/gedit-phpide/addiks_phpide/AddiksPHPIDEView.py", line 80, in __on_document_insert
    if document.get_location() != None and insertedText in ['\n', ';', '=', '}']:
AttributeError: 'Document' object has no attribute 'get_location'
Traceback (most recent call last):
  File "/home/wolfgang/.local/share/gedit/plugins/gedit-phpide/addiks_phpide/AddiksPHPIDEView.py", line 144, in __on_document_changed
    if document.get_location() != None:
AttributeError: 'Document' object has no attribute 'get_location'

```

**Comment by wblessen** [comment]
Plugin is activated after restart

**Comment by wblessen** [comment]
https://github.com/MicahCarrick/gedit-source-code-browser/issues/35

The object model of gedit has obviously changed. In the file "plugin.py" you need to replace the code "document.get_location()" to "document.get_file().get_location()". Then it works again.
