### ISSUE TITLE
Ubuntu 17.10 ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by ghost** [addiks/gedit-phpide#6]
```
(gedit:31692): Gtk-WARNING **: Allocating size to GtkOverlay 0x55bcc8a80cb0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?




(gedit:31692): libpeas-WARNING **: Error importing plugin 'addiks-phpide':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mre/.local/share/gedit/plugins/gedit-phpide/addiks-phpide.py", line 17, in <module>
    from addiks_phpide.AddiksPHPIDEApp import AddiksPHPIDEApp
  File "/home/mre/.local/share/gedit/plugins/gedit-phpide/addiks_phpide/AddiksPHPIDEApp.py", line 23, in <module>
    from .AddiksPhpGladeHandler import AddiksPhpGladeHandler
  File "/home/mre/.local/share/gedit/plugins/gedit-phpide/addiks_phpide/AddiksPhpGladeHandler.py", line 27, in <module>
    from .PHP.GraphMLExporter import GraphMLExporter
  File "/home/mre/.local/share/gedit/plugins/gedit-phpide/addiks_phpide/PHP/GraphMLExporter.py", line 19, in <module>
    from lxml import etree as xml
ModuleNotFoundError: No module named 'lxml'

(gedit:31692): libpeas-WARNING **: Error loading plugin 'addiks-phpide'
```

**Comment by ghost** [comment]
Did a `sudo apt-get install python-lxml` but still same error.

**Comment by addiks** [comment]
Did you try to install the package "python3-lxml"? On many distributions there are different packages for python-2 and python-3. 

If that does not help i need more information about the system you are using to replicate your situation in a virtual machine. What distribution? What version? What desktop? Any additional plugins installed? What python- and gedit-version are you using?

**Comment by ghost** [comment]
YES `sudo apt-get install python3-lxml` did it!
THANX!
Ubuntu 17.10 (mentioned in the title)

**Comment by addiks** [comment]
Glad i could help. :)
